### ISSUE TITLE
Update to Swift 5

### ISSUE THREAD

**Issue by lk251** [bhlvoong/LBTAComponents#33]
Hi! I love this library, will it be updated for Swift 5? Can we, its users, help in any way? Thank you.

**Comment by nitinnain** [comment]
You might be better off using the native iOS ways for arranging UI. This library is ok, but at some points just feels like an unnecessary wrapper. Maybe that's why the authour seems to have lost interest in continuing to keep it updated too. 
If you really want to use it, you can make a local copy and customise it to your liking. It'll migrate easily to Swift 5.

**Comment by lk251** [comment]
I think LBTAComponents is a much, much better way of doing things and I hope I can continue to use it. @bhlvoong thank you very much for making it and sharing it here!

**Comment by jesus-rod** [comment]
Actually it should be pretty easy to update. However, brian doesn't seem interested in doing so. I opened a PR for Swift 4.2 quite some time ago and no response there. Maybe just for it and update it yourself :)

**Comment by bhlvoong** [comment]
I didn't know so many people were still interested in using this library.  I've diverged a little from the logic in these libraries so a full update would introduce a lot of breaking code....

**Comment by lk251** [comment]
@bhlvoong I can't speak for anyone but myself, but I'd be very happy to see a full update, despite the breaking changes.

**Comment by bhlvoong** [comment]
Now compatible with Swift 5. However, I am deprecating this library in favor of LBTATools.
