### ISSUE TITLE
Division on two Pods

### ISSUE THREAD

**Issue by vyachesIavskiy** [bhlvoong/LBTAComponents#8]
Hello, Brian!
I finally decided to install your LBTAComponents and immediately found one issue: almost 400mb. And 95% of it is examples. So a little piece of advice: maybe two pods?

**Comment by bhlvoong** [comment]
It's showing up as 74KB on my hard drive.  Why is it almost half a gig on your computer?

**Comment by ZacharyKhan** [comment]
Mine is nowhere near 400mb, not sure what you're doing here. Showing as 250KB for me.

**Open terminal and type** `pod try LBTAComponents` and see how big that is. The pod should be even smaller since it won't contain the demo.

<img width="274" alt="screen shot 2017-12-05 at 5 24 24 pm" src="https://user-images.githubusercontent.com/14354004/33639652-3b4c02ae-d9e1-11e7-81f6-3b14c1530511.png">

**Comment by bhlvoong** [comment]
Yeah I WISH my library was 400mb, but sadly I don't have the time to write such a massive library.
